name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install -e .
          pip install pytest
      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q
      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: tests/*.pdf

      - name: Generate Numerology PDF
        run: python run_report.py --type numerology --input templates/numerology_sample.json --output output/numerology_ci.pdf

      - name: Generate Destiny Matrix PDF
        run: python run_report.py --type destiny_matrix --input templates/destinymatrix_sample.json --output output/destinymatrix_ci.pdf

      - name: Generate Astrocartography PDF
        run: python run_report.py --type astrocartography --input templates/astrocartography_sample.json --output output/astrocartography_ci.pdf

      - name: Generate Astrology PDF
        run: python run_report.py --type astrology --input templates/astrology_sample.json --output output/astrology_ci.pdf
