name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install local package
        run: pip install -e .
      - name: Install test tools
        run: pip install pytest
      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q
      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: tests/*.pdf
