name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install deps
        run: pip install -r requirements.txt pytest reportlab openai
      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q
      - name: Upload PDFs
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: tests/*.pdf
